service: Doterra-serverless

provider:
  name: aws
  runtime: nodejs14.x
  profile: doterraServerlessUser
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements: 
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: '*'
  httpApi:
    cors: true
  lambdaHashingVersion: 20201221

custom:
  tableName: Products
  
functions:
  getProduct:
    handler: lambdas/endpoints/getProduct.handler
    events:
      - httpApi:
          method: GET
          path: /get-product/{ID}
  addProduct:
    handler: lambdas/endpoints/addProduct.handler
    events:
      - httpApi:
          method: POST
          path: /add-product/{ID}

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
          

        




